openapi: 3.0.1
info:
  title: Api documentation
  version: 1.0.0
paths:
  /api/v1/info/addresses:
    get:
      operationId: infoControllerGetBridgeAddress
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoAddressResponseModel'
          description: Success
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
          description: Not found
      description: Return the addresses used in bridge
      summary: Get Bridge Addresses
      parameters: []
      tags:
        - InfoController
  /api/v1/info/fees:
    get:
      operationId: infoControllerGetFees
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeesResponseModel'
          description: Success
      description: Return the fees
      summary: Get fees
      parameters: []
      tags:
        - InfoController
  /healthz:
    get:
      operationId: healthCtrlHealth
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: object
          description: Success
      parameters: []
      tags:
        - HealthCtrl
  /readyz:
    get:
      operationId: readyCtrlReady
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: object
          description: Success
        '503':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnvailable'
          description: MySQL server is down
      parameters: []
      tags:
        - ReadyCtrl
tags:
  - name: InfoController
  - name: HealthCtrl
  - name: ReadyCtrl
components:
  schemas:
    NotFound:
      type: object
      properties:
        name:
          type: string
          description: The error name
          minLength: 1
          example: NOT_FOUND
          default: NOT_FOUND
        message:
          type: string
          description: An error message
          minLength: 1
        status:
          type: number
          description: The status code of the exception
          example: 404
          default: 404
        errors:
          type: array
          items:
            $ref: '#/components/schemas/GenericError'
          description: A list of related errors
        stack:
          type: string
          description: The stack trace (only in development mode)
      required:
        - name
        - message
        - status
    GenericError:
      type: object
      properties:
        name:
          type: string
          description: The error name
          minLength: 1
        message:
          type: string
          description: An error message
          minLength: 1
      additionalProperties: true
      required:
        - name
        - message
    InfoAddressResponseModel:
      type: object
      properties:
        XFUN_TOKEN_ADDRESS:
          type: string
          example: '0xaae15F8C22771Ea4A9bA9D4b7736472fa329a919'
          minLength: 1
        FUN_TOKEN_ADDRESS:
          type: string
          example: '0xEDB4c48d857Ec0315eEaee140D5c81Ee409a55b8'
          minLength: 1
        WALLET_PUBLIC_ADDRESS:
          type: string
          example: '0x18c4e974424C3Fa80f9B513C990D34a13c48AbE3'
          minLength: 1
        PAYMASTER_CONTRACT_ADDRESS:
          type: string
          example: '0x18c4e974424C3Fa80f9B513C990D34a13c48AbE3'
          minLength: 1
      required:
        - XFUN_TOKEN_ADDRESS
        - FUN_TOKEN_ADDRESS
        - WALLET_PUBLIC_ADDRESS
        - PAYMASTER_CONTRACT_ADDRESS
    FeesResponseModel:
      type: object
      properties:
        gasPrice:
          $ref: '#/components/schemas/GasPriceModel'
        funTokenPrice:
          $ref: '#/components/schemas/FunTokenPriceModel'
        fee:
          $ref: '#/components/schemas/FeeModel'
      required:
        - gasPrice
        - funTokenPrice
        - fee
    GasPriceModel:
      type: object
      properties:
        maxFeePerGas:
          type: string
          example: '119.955233893'
          minLength: 1
        maxPriorityFeePerGas:
          type: string
          example: '119.955233893'
          minLength: 1
      required:
        - maxFeePerGas
        - maxPriorityFeePerGas
    FunTokenPriceModel:
      type: object
      properties:
        ETH:
          type: string
          example: '0.00000364'
          minLength: 1
        USD:
          type: string
          example: '0.01049877'
          minLength: 1
      required:
        - ETH
        - USD
    FeeModel:
      type: object
      properties:
        FUN:
          type: string
          example: '2636'
          minLength: 1
        ETH:
          type: string
          example: '0.00959641871144'
          minLength: 1
      required:
        - FUN
        - ETH
    ServiceUnvailable:
      type: object
      properties:
        name:
          type: string
          description: The error name
          minLength: 1
          example: SERVICE_UNAVAILABLE
          default: SERVICE_UNAVAILABLE
        message:
          type: string
          description: An error message
          minLength: 1
        status:
          type: number
          description: The status code of the exception
          example: 503
          default: 503
        errors:
          type: array
          items:
            $ref: '#/components/schemas/GenericError'
          description: A list of related errors
        stack:
          type: string
          description: The stack trace (only in development mode)
      required:
        - name
        - message
        - status
